name: Check Test Coverage

on:
  workflow_dispatch:
  pull_request:
    branches: [dev, test, preprod, main]
    paths:
      - '.github/workflows/test.yaml'
      - 'src/services/**'

  push:
    branches: [dev, test, preprod, main]
    paths:
      - '.github/workflows/test.yaml'
      - 'src/services/**'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          for service in src/services/*; do
            if [ -d "$service" ]; then
              echo "Installing dependencies for $(basename "$service")..."
              cd "$service"
              go mod download
              cd -
            fi
          done

      - name: Run tests and collect coverage
        run: |
          for service in src/services/*; do
            service_name=$(basename "$service")
            echo "Service name: $service_name"
            if [ -d "$service/tests" ]; then
              (cd "$service" && \
              (go test -coverpkg=./... -coverprofile=coverage.out ./tests) &&  (go tool cover -func=coverage.out)) || exit 1
            elif [ -f "$service/main_test.go" ]; then
              (cd "$service" && \
              (go test -coverpkg=./... -coverprofile=coverage.out .) &&  (go tool cover -func=coverage.out)) || exit 1
            fi
            cd "$service"
            rm "coverage.out"
            cd -
          done

      - name: Post coverage comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            let coverageReport = '';
            for (const service of fs.readdirSync('src/services')) {
              const servicePath = path.join('src/services', service);
              if (fs.existsSync(path.join(servicePath, 'coverage.out'))) {
                const coverage = fs.readFileSync(path.join(servicePath, 'coverage.out'), 'utf8');
                coverageReport += `### ${service}\n\`\`\`\n${coverage}\n\`\`\`\n`;
              }
            }

            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `## Test Coverage Report\n${coverageReport}`
            });
